/*
 * Provide access to an autogenerated symbol table.
 */

#ifndef __SYMBOLS_H__
#define __SYMBOLS_H__

#include "types.h"

struct symbol {
	u32         addr;
	const char  sym[60];
};

struct symtable_header {
	u32 length;
};

const char *addr2sym(u32 addr, u32 *offset);
void        symtable_describe(void);

#endif
