include $(R5SIM_DIR)/build/riscv-xc.mk

INCLUDES  += -I$(R5SIM_DIR)/conftest

OBJS += env.o \
        ldst.o \
        muldiv.o \
        op.o \
        traps.o \
        sv_traps.o \
        system.o
