#!/usr/bin/python3
#
# Take our input, in the form of NM's output, and generate a C file
# that turns this into an array of address -> name pairs.
#

import sys

entries = 0

# Some prologue for the symbol table.
print(
    """/*
 * This file is AUTOGENERATED! Do not edit by hand. This is generated
 * by syms.py.
 */

.section	.rodata.symtable
""")

for line in sys.stdin:
    __addr, symtype, name = line.split()

    addr = int(__addr, 16)

    print("\t.word  0x%x" % addr)
    print("\t.ascii \"%s\"" % name[0:59])
    print("\t.balign 64")

    entries += 1

# Now print the table header info.
print("")
print(".section	.rodata.symtable.header")
print("\t.word  %d /* length */" % entries)
